### ISSUE TITLE
HookWebpackError: Expected a pseudo-class or pseudo-element w/ NextJS

### ISSUE THREAD

**Issue by eiiot** [Timer/cssnano-simple#30]
I get the following error when running `next build`:

```
HookWebpackError: Expected a pseudo-class or pseudo-element.
    at makeWebpackError (/Users/eliot/Developer/eliothertenstein.com/node_modules/next/dist/compiled/webpack/bundle5.js:28:308185)
    at /Users/eliot/Developer/eliothertenstein.com/node_modules/next/dist/compiled/webpack/bundle5.js:28:105236
    at eval (eval at create (/Users/eliot/Developer/eliothertenstein.com/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:34:1)
-- inner error --
Error: Expected a pseudo-class or pseudo-element.
    at /Users/eliot/Developer/eliothertenstein.com/static/css/66780ddc5f37cb3b.css:906:3
    at Root._error (/Users/eliot/Developer/eliothertenstein.com/node_modules/next/dist/compiled/cssnano-simple/index.js:190:78465)
    at Root.error (/Users/eliot/Developer/eliothertenstein.com/node_modules/next/dist/compiled/cssnano-simple/index.js:190:124360)
    at Parser.error (/Users/eliot/Developer/eliothertenstein.com/node_modules/next/dist/compiled/cssnano-simple/index.js:190:86811)
    at Parser.expected (/Users/eliot/Developer/eliothertenstein.com/node_modules/next/dist/compiled/cssnano-simple/index.js:190:93145)
    at Parser.pseudo (/Users/eliot/Developer/eliothertenstein.com/node_modules/next/dist/compiled/cssnano-simple/index.js:190:89313)
    at Parser.parse (/Users/eliot/Developer/eliothertenstein.com/node_modules/next/dist/compiled/cssnano-simple/index.js:190:92668)
    at Parser.loop (/Users/eliot/Developer/eliothertenstein.com/node_modules/next/dist/compiled/cssnano-simple/index.js:190:92233)
    at new Parser (/Users/eliot/Developer/eliothertenstein.com/node_modules/next/dist/compiled/cssnano-simple/index.js:190:78322)
    at Processor._root (/Users/eliot/Developer/eliothertenstein.com/node_modules/next/dist/compiled/cssnano-simple/index.js:190:95242)
    at Processor._runSync (/Users/eliot/Developer/eliothertenstein.com/node_modules/next/dist/compiled/cssnano-simple/index.js:190:95749)
caused by plugins in Compilation.hooks.processAssets
```

(See the full error at https://pastebin.com/JLQ2aR2f)

I've been trying to debug this issue for ~3hrs, and it's driving me crazy. I would appreciate any help on how I could better debug the `next build` command? I tried using the `--debug` flag, but it didn't seem to do anything.

So far I know this is an issue with `tailwindcss` (I assume `postcss`),  as when I remove that section of my `global.scss` the program works again (or actually after I comment out the full file EXCEPT for tailwind it still breaks, commenting out tailwind leads to other issues).

Oh, some other debugging I've tried:

- Searching through my entire project w/ regex to find any invliad tailwind classes (using `(["'])(.*\b\w+: )(.*)(\1)` to locate classes like `md: text-red-600` but not `md:text-red-600`)
- reinstalled all `node_modules`
- commenting out all CSS files (which stops the issue!)
- used both `yarn classic` and `node` to run the command (and `npx`) as opposed to `yarn v3` which is what I currently use for development

Maybe it's a debugging issue? More clarify on how I can diagnose and fix this error would be appreciated.

**Comment by eiiot** [comment]
It turns out the answer was an error in `tailwind.config.js`. One of my keyframes looked like this:

```
expand: {
 ...
 '80%:': {
   opacity: 0.5,
  },
  ...
},
```

Notice the double semicolon after `80%`. I would encourage everyone with this issue to check `classNames`, `.css` files, and also `tailwind.config.js` for any extra colons.

Also: is there any way to make this easier to debug? I basically wasted an entire day just trying to fix this one error.
